### ISSUE TITLE
打卡需要定位导致不能在电脑端微信打卡

### ISSUE THREAD

**Issue by ladeng07** [ExistoT01/auto-checkin-script#3]
不能在电脑打卡，怎么抓包呢？

**Comment by ExistoT01** [comment]
> 如果上报表单中有录音/签名/位置/拍照项，是不支持网页请求打卡的，需要用小程序端打卡，但是「只要录音/签名/位置/拍照项不是必要项，你依然可以使用网页请求打卡」

只要「定位」那一项不是必要的就可以在电脑抓，如果是就没办法了，手机也有抓包的办法不过稍微麻烦点，用「fidder」保持电脑手机在同一局域网也可以抓包，详细可以去google
